[package]
name = "http_outcall_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9"
ic-cdk = "0.11"
ic-cdk-macros = "0.8.0"
serde = "1.0"
serde_json = "1.0"
serde_qs = "0.12.0"
