[package]
name = "http_incoming_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.21.5"
candid = "0.9"
ic-cdk = "0.11"
serde = "1.0.193"
